"""Service layer: orchestration and business logic between pages and data.

Architecture: pages/ (UI) → services/ (orchestration) → data.py (persistence)
"""

from handoff.services.dashboard_service import (
    get_cycle_time_by_project,
    get_dashboard_metrics,
    get_deadline_adherence_trend,
    get_exportable_metrics,
    get_per_pitchman_throughput,
    get_per_project_throughput,
    get_pitchman_load,
    get_weekly_throughput,
)
from handoff.services.handoff_service import (
    add_check_in,
    conclude_handoff,
    create_handoff,
    delete_handoff,
    get_handoff_close_date,
    list_pitchmen,
    list_pitchmen_with_open_handoffs,
    query_action_handoffs,
    query_concluded_handoffs,
    query_handoffs,
    query_now_items,
    query_risk_handoffs,
    query_upcoming_handoffs,
    reopen_handoff,
    snooze_handoff,
    update_handoff,
)
from handoff.services.project_service import (
    archive_project,
    create_project,
    delete_project,
    get_projects_with_handoff_summary,
    list_projects,
    rename_project,
    unarchive_project,
)
from handoff.services.settings_service import (
    get_deadline_near_days,
    get_export_payload,
    import_payload,
    set_deadline_near_days,
)

__all__ = [
    "add_check_in",
    "archive_project",
    "conclude_handoff",
    "create_handoff",
    "create_project",
    "delete_handoff",
    "delete_project",
    "get_cycle_time_by_project",
    "get_dashboard_metrics",
    "get_deadline_adherence_trend",
    "get_handoff_close_date",
    "get_deadline_near_days",
    "get_exportable_metrics",
    "get_export_payload",
    "get_per_pitchman_throughput",
    "get_per_project_throughput",
    "get_pitchman_load",
    "get_projects_with_handoff_summary",
    "get_weekly_throughput",
    "import_payload",
    "list_pitchmen",
    "list_pitchmen_with_open_handoffs",
    "list_projects",
    "query_action_handoffs",
    "query_concluded_handoffs",
    "query_handoffs",
    "query_now_items",
    "query_risk_handoffs",
    "query_upcoming_handoffs",
    "reopen_handoff",
    "rename_project",
    "set_deadline_near_days",
    "snooze_handoff",
    "unarchive_project",
    "update_handoff",
]
